name: Build Assets

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm 7
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        # 从分支名中获取版本号release/v1.0.0 => 1.0.0
        run: echo "VERSION=$(echo $BRANCH_NAME | sed 's/release\/v//g')" >> $GITHUB_ENV

      - name: Build
        run: npm run build && node ./scripts/build-assets.js --version ${{ env.VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'lcap-template@${{ env.VERSION }}'
          path: temp
