name: Build Assets

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
    inputs:
      version:
        description: '自定义版本号'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm 8
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        # 从分支名中获取版本号, 如分支名release/v1.0.0，获取到1.0.0；如果分支名不符合规范，则不设置VERSION变量
        run: 
          echo "VERSION=$(echo $BRANCH_NAME | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | cut -c 2-)" >> $GITHUB_ENV

      # 版本号优先取自定义版本号，其次取分支名中的版本号
      - name: Get version from input
        if: ${{ inputs.version }}
        run: echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
      
      # 如果版本号不匹配a.b.c格式，则使用lerna.json中的版本号
      - name: Get version from lerna.json
        if: ${{ !env.VERSION }}
        run: echo "VERSION=$(cat lerna.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Build
        run: npm run build && node ./scripts/copy-assets.js --version ${{ env.VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'lcap-template@${{ env.VERSION }}'
          path: temp
