name: Build and Deploy

on:
  push:
    branches:
      - test
      - test/**
      - test-**

jobs:
  call-tyler:
    uses: netease-lcap/tyler/.github/workflows/deploy-ui-libraries.yml@master
    secrets: inherit
