name: Build Assets

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Get current branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Get version from branch name
        run: echo "VERSION=$(echo ${{ env.BRANCH_NAME }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Build
        run: npm run build:designer

      # 创建一个临时目录
      - name: Create temp dir
        run: mkdir temp && cp -r ./public ./temp

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'mobile-template@${{ env.VERSION }}'
          path: temp
