name: Build and Deploy

on:
  push:
    branches:
      - test
      - test/**
      - test-**

jobs:
  call-tyler:
    uses: netease-lcap/giselle/.github/workflows/deploy-lcap-template.yml@master
    secrets: inherit
